version: '3.8'

services:
  frontend_application:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_API_URL: 'http://docker_compose_vue_application.test'
    ports:
      - '8080:8080'
